curl --url 'http://localhost:8080/realms/test_realm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=test-client' \
--data-urlencode 'client_secret=F34gjpncG8iqSv6hgM3lnnKMQdzlEXlk'


curl --url  http://localhost:8081/health --request GET --header 'Authorization: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJEbnZXM1JLN2tSeVNwS1dZWmZzRnViYkNRWGw2MkJ5ZVhieGxNN1ctLTJRIn0.eyJleHAiOjE2OTkwNzA3MjksImlhdCI6MTY5OTA3MDQyOSwianRpIjoiZWE1ZmE0NDMtMDRkMS00NzNiLWIzMWItMGQ5MDE1Y2NiYjY2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0X3JlYWxtIiwic3ViIjoiZWZlMDY4YzctMmNjNi00YzEyLTk5NzctMTEwNWY5YmVjN2JlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidGVzdC1jbGllbnQiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwic2NvcGUiOiJoZWFsdGhfY2hlY2tfc2NvcGUiLCJjbGllbnRIb3N0IjoiMTcyLjE4LjAuMSIsImNsaWVudEFkZHJlc3MiOiIxNzIuMTguMC4xIiwiY2xpZW50X2lkIjoidGVzdC1jbGllbnQifQ.n-FeYx2nm7YxBo1hJard7jC7khXPipUKMj3a3RCTEj9IX_jeJYmWCYgNJOVbE-Linn7GpgQcfgQ1tY90DopYoThMYSSKIq9ki_3YiB9UD1SUxTQUEZYjDYCmAuujz4PGCSfchdWAHQmCXaPqxQkjzoWKKIMcPwZCUf8XbaKsUlSVL9sk6Q42cf2S70oGgX_tr7qwZ1BtQLFl8zhrVgS3c7p_DNF__PVDdCkYlTUp-eJdqKqCT57plOa7ZsCAup8OKx8Etfde59IHLHSRwVSBvih79cRiVFrUZNpv450frjwJ8ilsc_FGdqyM4liiRYbLa2OOf1rXHqKjgXWCGMfqqA' -v